[graph]
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "BSL-1.0",
]
confidence-threshold = 0.93
unused-allowed-license = "allow"
exceptions = []
private = { ignore = true }

[bans]
multiple-versions = "warn"
skip = []

[advisories]
ignore = []
