#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Runs the Panelist example dashboards against a real Grafana, backed by a
# synthetic Prometheus and Loki, and renders each one to a PNG.
#
# The dashboards Grafana serves are generated by running the examples
# themselves, so the gallery images cannot drift from the code they
# illustrate: regenerating an image reruns `cargo run --example <name>`.
#
# Usage:
#   scripts/demo.sh up       boot the stack and provision every example
#   scripts/demo.sh render   render each dashboard into examples/images
#   scripts/demo.sh down     stop the stack and delete its volumes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEMO_DIR="${REPO_ROOT}/examples/demo"
DASHBOARD_DIR="${DEMO_DIR}/grafana/dashboards"
IMAGE_DIR="${REPO_ROOT}/examples/images"
COMPOSE=(docker compose -f "${DEMO_DIR}/compose.yml")

GRAFANA_URL="${DEMO_GRAFANA_URL:-http://localhost:3000}"
PROMETHEUS_URL="${DEMO_PROMETHEUS_URL:-http://localhost:9090}"
BOOT_TIMEOUT_SECONDS="${DEMO_BOOT_TIMEOUT_SECONDS:-180}"

# Prometheus can only graph what it has scraped since boot, so a render
# taken immediately after `up` would show a mostly empty time axis.
WARMUP_SECONDS="${DEMO_WARMUP_SECONDS:-300}"
SCRAPE_INTERVAL_SECONDS=5

RENDER_WIDTH="${DEMO_RENDER_WIDTH:-1600}"
RENDER_TIMEOUT_SECONDS="${DEMO_RENDER_TIMEOUT_SECONDS:-120}"

# Variables that a render has to pin. Grafana resolves an unset variable
# from whatever the datasource returns first, which would make the same
# dashboard render differently from one run to the next.
#
# A `case` rather than an associative array: macOS ships bash 3.2, where
# `declare -A` quietly declares an *indexed* array instead and then
# arithmetic-evaluates each key, so "route-performance" is read as the
# variable `route` minus the variable `performance`.
dashboard_vars() {
  case "$1" in
    route-performance) echo "var-route=%24__all" ;;
    geoip) echo "var-instance=%24__all" ;;
    variables) echo "var-environment=production&var-instance=%24__all" ;;
    *) echo "" ;;
  esac
}

log() { echo "==> $*"; }
die() { echo "FAILED: $*" >&2; exit 1; }

require_tools() {
  local missing=()
  for tool in docker curl jq cargo; do
    command -v "${tool}" >/dev/null 2>&1 || missing+=("${tool}")
  done
  [ "${#missing[@]}" -eq 0 ] || die "missing required tools: ${missing[*]}"
  docker info >/dev/null 2>&1 || die "Docker is not running"
}

# Renders every example to JSON in the directory Grafana provisions from.
generate_dashboards() {
  log "Generating dashboards from the examples"
  mkdir -p "${DASHBOARD_DIR}"
  rm -f "${DASHBOARD_DIR}"/*.json

  local count=0
  for source in "${REPO_ROOT}"/crates/panelist/examples/*.rs; do
    local name uid target
    name="$(basename "${source}" .rs)"
    target="${DASHBOARD_DIR}/${name}.json"

    cargo run --quiet --manifest-path "${REPO_ROOT}/Cargo.toml" \
      -p panelist --example "${name}" >"${target}" \
      || die "example ${name} did not run"

    uid="$(jq -r '.uid // empty' "${target}")"
    [ -n "${uid}" ] || die "example ${name} emitted no uid, so it cannot be provisioned"
    count=$((count + 1))
    printf '    %-20s uid=%s\n' "${name}" "${uid}"
  done
  [ "${count}" -gt 0 ] || die "no examples found to generate"
}

wait_for_url() {
  local label="$1" url="$2" filter="$3" elapsed=0
  log "Waiting for ${label} (timeout ${BOOT_TIMEOUT_SECONDS}s)"
  until curl -fsS "${url}" 2>/dev/null | jq -e "${filter}" >/dev/null 2>&1; do
    if [ "${elapsed}" -ge "${BOOT_TIMEOUT_SECONDS}" ]; then
      "${COMPOSE[@]}" logs --tail 40 >&2 || true
      die "${label} did not come up within ${BOOT_TIMEOUT_SECONDS}s"
    fi
    sleep 3
    elapsed=$((elapsed + 3))
  done
}

# Seconds of scraped history Prometheus currently holds, measured by how
# many `up` samples exist rather than by how long the container has run:
# that keeps a re-render of an already-warm stack from waiting again.
history_seconds() {
  local samples
  samples="$(curl -fsS --get "${PROMETHEUS_URL}/api/v1/query" \
    --data-urlencode 'query=max(count_over_time(up[6h]))' 2>/dev/null |
    jq -r '.data.result[0].value[1] // "0"')"
  python3 -c "import sys; print(int(float(sys.argv[1]) * ${SCRAPE_INTERVAL_SECONDS}))" "${samples}"
}

cmd_up() {
  require_tools
  generate_dashboards

  log "Starting the demo stack"
  "${COMPOSE[@]}" up -d

  # Deliberately not `up --wait`: without healthchecks it only waits for the
  # containers to be *running*, which Grafana is well before it has finished
  # provisioning. The polls below wait for the things that actually matter.
  wait_for_url "Grafana" "${GRAFANA_URL}/api/health" '.database == "ok"'
  wait_for_url "scrape targets" \
    "${PROMETHEUS_URL}/api/v1/query?query=count(up==1)" \
    '.data.result[0].value[1] | tonumber >= 5'

  local provisioned
  provisioned="$(curl -fsS "${GRAFANA_URL}/api/search?type=dash-db" | jq 'length')"
  log "Grafana has provisioned ${provisioned} dashboards"
  [ "${provisioned}" -ge 6 ] || die "expected 6 provisioned dashboards, found ${provisioned}"

  echo
  log "Grafana:    ${GRAFANA_URL} (anonymous admin)"
  log "Prometheus: ${PROMETHEUS_URL}"
  log "Stop with:  make demo-down"
}

# A screenshot of six "No data" panels is worse than no screenshot: it
# looks like the library produced an empty dashboard. Each of these
# queries backs at least one panel, so an empty result here means an image
# that would misrepresent the example.
verify_data() {
  log "Checking that every datasource actually has data"
  local expression label failures=0
  while IFS='|' read -r label expression; do
    [ -n "${label}" ] || continue
    local value
    value="$(curl -fsS --get "${PROMETHEUS_URL}/api/v1/query" \
      --data-urlencode "query=${expression}" 2>/dev/null |
      jq -r '.data.result[0].value[1] // "empty"')"
    if [ "${value}" = "empty" ] || [ "${value}" = "0" ]; then
      echo "    MISSING  ${label}  (${expression} returned ${value})" >&2
      failures=$((failures + 1))
    else
      printf '    ok       %-28s %s\n' "${label}" "${value}"
    fi
  done <<'QUERIES'
basic traffic|sum(rate(requests_total[5m]))
route traffic|sum(rate(http_requests_total[5m]))
route latency|histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))
geoip traffic|sum(rate(geoip_http_requests_total[5m]))
geoip resolutions|sum(rate(geoip_resolutions_total[5m]))
checkout traffic|sum(rate(checkout_requests_total[5m]))
geoip targets up|sum(up{job="geoip"})
checkout targets up|sum(up{job="checkout"})
variable instances|count(count by (instance) (up{environment="production"}))
QUERIES

  local loki_url="${DEMO_LOKI_URL:-http://localhost:3100}"
  local start end streams
  end="$(date +%s)000000000"
  start="$(( $(date +%s) - 3600 ))000000000"
  streams="$(curl -fsS --get "${loki_url}/loki/api/v1/query_range" \
    --data-urlencode 'query={service="geoip"} |= "resolution failed"' \
    --data-urlencode "start=${start}" --data-urlencode "end=${end}" \
    --data-urlencode "limit=5" 2>/dev/null | jq -r '.data.result | length')"
  if [ "${streams:-0}" -gt 0 ]; then
    printf '    ok       %-28s %s streams\n' "geoip failure logs" "${streams}"
  else
    echo "    MISSING  geoip failure logs (Loki returned no matching streams)" >&2
    failures=$((failures + 1))
  fi

  [ "${failures}" -eq 0 ] || die "${failures} datasource checks came back empty"
}

# Grafana lays panels out on a 24-column grid of 30px cells with an 8px
# gutter, so a grid unit is 38px tall. Rendering at a fixed height would clip
# the taller dashboards and pad the short ones with dead space, so the height
# comes from the dashboard's own grid.
#
# The 130px of chrome was measured, not guessed: rendering
# `route_performance` (43 grid units) into an oversized viewport put the last
# content pixel at row 1690, which is 43 * 38 + 56 for the controls bar. The
# remaining ~74px is clearance for the "Powered by Grafana" footer, which is
# pinned to the bottom of the viewport rather than placed after the content -
# size the viewport to the content exactly and the footer sits on top of the
# last panel.
render_height() {
  local file="$1" units
  units="$(jq '[.panels[] | .gridPos.y + .gridPos.h] | max // 12' "${file}")"
  python3 -c "print(min(3200, max(400, int($units) * 38 + 130)))"
}

cmd_render() {
  require_tools

  # Always regenerate before rendering. Skipping this when the stack happens
  # to be up already would let an image be rendered from whatever JSON was
  # provisioned earlier, which is exactly the drift these images exist to
  # rule out. `cmd_up` generates on its own, so only the warm-stack path
  # needs to do it here.
  if curl -fsS "${GRAFANA_URL}/api/health" 2>/dev/null | jq -e '.database == "ok"' >/dev/null 2>&1; then
    generate_dashboards
    log "Waiting for the provisioner to reload (updateIntervalSeconds: 5)"
    sleep 8
  else
    cmd_up
  fi

  local history
  history="$(history_seconds)"
  if [ "${history}" -lt "${WARMUP_SECONDS}" ]; then
    local remaining=$((WARMUP_SECONDS - history))
    log "Warming up: ${history}s of history, waiting ${remaining}s for ${WARMUP_SECONDS}s"
    sleep "${remaining}"
    history="$(history_seconds)"
  fi

  # Widen the window to whatever history exists, so leaving the stack up
  # produces a better screenshot instead of the same five-minute one.
  local window
  if [ -n "${DEMO_WINDOW:-}" ]; then window="${DEMO_WINDOW}"
  elif [ "${history}" -ge 3600 ]; then window="now-1h"
  elif [ "${history}" -ge 1800 ]; then window="now-30m"
  elif [ "${history}" -ge 900 ]; then window="now-15m"
  else window="now-5m"
  fi
  log "Rendering with ${history}s of history over ${window}"

  verify_data

  mkdir -p "${IMAGE_DIR}"
  local rendered=0
  for file in "${DASHBOARD_DIR}"/*.json; do
    local name uid height url target vars
    name="$(basename "${file}" .json)"
    uid="$(jq -r '.uid' "${file}")"
    height="$(render_height "${file}")"
    vars="$(dashboard_vars "${uid}")"
    target="${IMAGE_DIR}/${name}.png"

    url="${GRAFANA_URL}/render/d/${uid}/${name}?orgId=1&from=${window}&to=now"
    url="${url}&width=${RENDER_WIDTH}&height=${height}&theme=dark&kiosk&tz=UTC"
    [ -z "${vars}" ] || url="${url}&${vars}"

    printf '    %-20s %sx%s ... ' "${name}" "${RENDER_WIDTH}" "${height}"
    curl -fsS --max-time "${RENDER_TIMEOUT_SECONDS}" -o "${target}" "${url}" ||
      die "render request failed for ${name}"

    # Grafana answers a failed render with JSON, and a renderer timeout with
    # a near-empty PNG, both with HTTP 200. Check the bytes, not the status.
    python3 - "${target}" "${name}" <<'PY'
import pathlib, sys

path, name = pathlib.Path(sys.argv[1]), sys.argv[2]
data = path.read_bytes()
if not data.startswith(b"\x89PNG\r\n\x1a\n"):
    sys.exit(f"{name}: not a PNG, got {data[:120]!r}")
if len(data) < 20_000:
    sys.exit(f"{name}: PNG is only {len(data)} bytes, the render likely timed out")
print(f"{len(data) // 1024} KiB")
PY
    rendered=$((rendered + 1))
  done

  log "Rendered ${rendered} dashboards into examples/images"
  log "The stack is still up. Stop it with: make demo-down"
}

cmd_down() {
  log "Stopping the demo stack"
  "${COMPOSE[@]}" down --volumes --remove-orphans
  rm -f "${DASHBOARD_DIR}"/*.json
}

case "${1:-}" in
  up) cmd_up ;;
  render) cmd_render ;;
  down) cmd_down ;;
  *)
    echo "Usage: scripts/demo.sh {up|render|down}" >&2
    exit 2
    ;;
esac
